spring.application.name=ADFA
spring.datasource.url=jdbc:mysql://localhost:3306/adfa_test
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true